const fragments = [
 {symbol:'○',title:'O vazio',hint:'Nem todo silêncio significava falta de amor.',text:'Nesses últimos tempos eu me senti vazio algumas vezes. Não porque eu deixei de amar você, mas porque a cada dia parecia que a gente precisava atravessar uma dificuldade nova.',secret:'O medo de te perder ficou muito alto dentro de mim. Às vezes bastava um dia estranho, algumas horas diferentes ou uma conversa que não saía como eu esperava para minha cabeça imaginar mil finais. Hoje eu entendo que amar você também significa aprender a não deixar esse medo falar mais alto que a confiança que eu tenho em nós.'},
 {symbol:'⌁',title:'O cansaço',hint:'O peso não era você. Era tudo o que eu carregava sem saber organizar.',text:'Teve momentos em que o cansaço bateu forte em mim. Mas eu quero que você saiba de uma coisa: eu não estava cansado de você.',secret:'Eu estava cansado dos meus medos, das inseguranças, de algumas atitudes minhas e de ficar lutando contra pensamentos que eu mesmo criava. Você não era o problema. Muitas vezes, o que eu precisava era aprender a respirar, confiar e não transformar meu medo em peso para você.'},
 {symbol:'⋯',title:'As lágrimas',hint:'Algumas lágrimas nasceram de coisas pequenas; outras deixaram marcas grandes.',text:'Me desculpa por todas as vezes em que eu chorei por coisas que, olhando com calma, poderiam ter sido resolvidas de outra forma.',secret:'E principalmente me desculpa pelas vezes em que minhas atitudes fizeram você chorar. Eu não posso voltar e apagar esses momentos. Posso reconhecer, aprender e tentar fazer diferente. Eu quero que minhas próximas atitudes sejam uma parte muito mais bonita da nossa história do que os erros que já cometi.'},
 {symbol:'△',title:'O medo',hint:'Ele tentou transformar um dia ruim em uma despedida inteira.',text:'Às vezes meu medo de perder você fazia qualquer distância parecer enorme.',secret:'Eu quero aprender a diferenciar um dia difícil de um fim. Uma discussão de uma despedida. Seu cansaço de falta de amor. Porque você merece poder ter seus dias ruins sem precisar carregar também o medo que existe dentro de mim.'},
 {symbol:'∞',title:'O futuro',hint:'Tem uma imagem que fica cada vez mais nítida quando penso em você.',text:'A cada dia que passa, aumenta em mim a vontade de casar com você, ter filhos e construir nossa família.',secret:'Eu imagino coisas simples: nossa casa, nossas rotinas, uma criança correndo pela sala, nós dois reclamando de sono e depois rindo disso. Não porque eu ache que tudo vai ser perfeito, mas porque, quando penso em enfrentar a vida de verdade, é você que eu imagino do meu lado.'},
 {symbol:'↝',title:'A saudade',hint:'Tem uma distância que meu coração já cansou de medir.',text:'Eu tô doido de saudade de você. Saudade de te ver de verdade, de ficar perto e de transformar conversa em abraço.',secret:'Tem dias em que eu queria simplesmente pular toda a distância entre a gente. Chegar aí, te abraçar sem pressa e não precisar explicar nada. Só ficar. Porque algumas coisas que eu sinto por você não cabem em uma tela.'},
 {symbol:'◇',title:'A segurança',hint:'Mesmo quando a vida pesa, existe um lugar onde eu ainda consigo descansar.',text:'Eu sei que você também enfrenta dificuldades. Algumas se parecem com as minhas, outras são só suas. E eu não quero diminuir nenhuma delas.',secret:'Mesmo atravessando minhas próprias dificuldades, eu ainda me sinto seguro, amado e acolhido por você. Isso é uma das coisas que eu mais valorizo entre nós. Eu quero ser capaz de oferecer a você essa mesma sensação: presença sem pressão, carinho sem cobrança e confiança mesmo nos dias confusos.'},
 {symbol:'♡',title:'Nós',hint:'Depois de tudo, ainda existe uma palavra que eu escolheria.',text:'Eu nunca quero que amar você signifique prender você. Quero que signifique escolher você e também aprender a cuidar melhor de nós.',secret:'Eu não quero te deixar quando as coisas ficarem difíceis. Quero crescer, corrigir o que precisa ser corrigido e construir algo mais leve ao seu lado. Não quero prometer perfeição. Quero prometer esforço verdadeiro, respeito e atitudes que façam você sentir o amor que eu tantas vezes tento colocar em palavras.'}
];

const cards=document.getElementById('cards'), dialog=document.getElementById('messageDialog'), revealed=new Set();
fragments.forEach((f,i)=>{const b=document.createElement('button');b.className='card';b.innerHTML=`<span class="num">0${i+1}</span><span class="symbol">${f.symbol}</span><h3>${f.title}</h3><p>toque para descobrir a dica</p>`;b.onclick=()=>openFragment(i,b);cards.appendChild(b)});
function openFragment(i,card){const f=fragments[i];dialog.dataset.i=i;document.getElementById('dialogIndex').textContent=String(i+1).padStart(2,'0');document.getElementById('dialogTitle').textContent=f.title;document.getElementById('dialogText').textContent=f.hint;document.getElementById('secretMessage').classList.remove('visible');document.getElementById('secretMessage').innerHTML=`<p>${f.text}</p><p>${f.secret}</p>`;document.getElementById('revealBtn').style.display='block';dialog.showModal();card.classList.add('active')}
document.getElementById('revealBtn').onclick=()=>{const i=+dialog.dataset.i;document.getElementById('secretMessage').classList.add('visible');document.getElementById('revealBtn').style.display='none';revealed.add(i);cards.children[i].classList.add('opened');updateProgress()};
function updateProgress(){document.getElementById('progressText').textContent=`${revealed.size} / 8 fragmentos`;document.getElementById('progressBar').style.width=`${revealed.size/8*100}%`;if(revealed.size===8){document.getElementById('gameSection').classList.remove('locked');toast('O último lugar foi desbloqueado ✦')}}
document.getElementById('closeDialog').onclick=()=>dialog.close();document.getElementById('startBtn').onclick=()=>document.getElementById('fragmentos').scrollIntoView({behavior:'smooth'});
const themeToggle=document.getElementById('themeToggle');themeToggle.onclick=()=>{const soft=document.documentElement.dataset.theme==='soft';document.documentElement.dataset.theme=soft?'dark':'soft';document.getElementById('themeName').textContent=soft?'Super escuro':'Claro suave';localStorage.setItem('gaby-theme',soft?'dark':'soft')};const saved=localStorage.getItem('gaby-theme');if(saved){document.documentElement.dataset.theme=saved;document.getElementById('themeName').textContent=saved==='soft'?'Claro suave':'Super escuro'}
let taps=0;document.getElementById('brandSecret').onclick=()=>{taps++;if(taps===4){toast('segredo: mesmo quando nada parece perfeito, você ainda é meu lugar favorito.');taps=0}}
function toast(t){const el=document.getElementById('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3200)}

const feelings=['cansaço','medo','insegurança','saudade','dias difíceis','esperança'];const positions=[[9,14],[68,12],[7,72],[70,75],[3,43],[74,45]];const orbit=document.getElementById('orbit');let selected=null,absorbed=0;
feelings.forEach((name,i)=>{const b=document.createElement('button');b.className='feeling';b.textContent=name;b.style.left=positions[i][0]+'%';b.style.top=positions[i][1]+'%';b.onclick=()=>{if(b.classList.contains('absorbed'))return;document.querySelectorAll('.feeling').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=b;document.getElementById('gameTip').textContent=`“${name}” não precisa ficar sozinho. Agora toque em NÓS.`};orbit.appendChild(b)});
document.getElementById('usCore').onclick=()=>{if(!selected){toast('Escolha um sentimento primeiro.');return}const board=document.getElementById('gameBoard').getBoundingClientRect(),r=selected.getBoundingClientRect();selected.style.setProperty('--dx',`${board.left+board.width/2-(r.left+r.width/2)}px`);selected.style.setProperty('--dy',`${board.top+board.height/2-(r.top+r.height/2)}px`);selected.classList.remove('selected');selected.classList.add('absorbed');absorbed++;document.getElementById('coreCount').textContent=`${absorbed} / 6`;selected=null;const messages=['Cansaço dividido pesa menos.','O medo pode existir sem decidir nosso futuro.','Insegurança precisa de cuidado, não de guerra.','Saudade também é prova de presença.','Um dia difícil continua sendo só um dia.','E no meio de tudo… ainda existe esperança.'];document.getElementById('gameTip').textContent=messages[absorbed-1];if(absorbed===6)setTimeout(()=>{document.getElementById('finale').hidden=false;document.getElementById('finale').scrollIntoView({behavior:'smooth',block:'center'})},700)};
document.getElementById('finalLetterBtn').onclick=()=>document.getElementById('letterDialog').showModal();document.getElementById('closeLetter').onclick=()=>document.getElementById('letterDialog').close();
[dialog,document.getElementById('letterDialog')].forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}));
